---

- name: Update apt-get repo and cache
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: install dependencies
  ansible.builtin.package:
    name:
      - apache2
      - ghostscript
      - libapache2-mod-php
      - mysql-server
      - php
      - php-bcmath
      - php-curl
      - php-imagick
      - php-intl
      - php-json
      - php-mbstring
      - php-mysql
      - php-xml
      - php-zip
    state: present

- name: Create the installation directory
  ansible.builtin.file:
    path: /srv/www
    owner: www-data
    state: directory
    mode: 0755

- name: Install WordPress
  ansible.builtin.unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /srv/www
    owner: www-data
    remote_src: yes

- name: Copy file with owner and permissions
  ansible.builtin.template:
    src: wordpress.conf.j2
    dest: /etc/apache2/sites-available/wordpress.conf
    owner: "www-data"
    mode: 0755

- name: Enable URL rewriting
  community.general.apache2_module:
    name: rewrite
    state: present

- name: Enable the site
  ansible.builtin.command:
    cmd: a2ensite wordpress
  changed_when: False

- name: Disable the default "It Works" site
  ansible.builtin.command:
    cmd: a2dissite 000-default
  changed_when: False

- name: Reload service apache2
  ansible.builtin.service:
    name: apache2
    state: reloaded

- name: Install mysql cert
  ansible.builtin.copy:
    src: root.crt
    dest: /usr/local/share/ca-certificates/root.crt
    mode: 0755

- name: Update cert index
  ansible.builtin.command:
    cmd: /usr/sbin/update-ca-certificates
  changed_when: False

- name: Configure WordPress
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: "/srv/www/wordpress/wp-config.php"
    owner: "www-data"
    mode: 0755